services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    user: 'root'
    volumes:
      - .:/app
    # to debug in the container uncomment below
    # then use use > docker compose up -d 
    # > docker compose exec app /bin/bash
    # lastly run jupyter using > uv pip install notebook and 
    # > jupyter notebook --allow-root --ip 0.0.0.0 --no-browser
    ports:
      - 8888:8888
    tty: true